/** Define ids for each page. */
export const PAGE_IDS = {
  ADD_STUFF: 'add-stuff',
  ADD_MEDICINE: 'add-medicine',
  ADD_SUPPLY: 'add-supply',
  EDIT_STUFF: 'edit-stuff',
  EDIT_SUPPLY: 'edit-supply',
  EDIT_MEDICINE: 'edit-medicine',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  LIST_MEDICINES: 'list-medicines',
  LIST_HISTORIES: 'list-histories',
  MANAGE_DATABASE: 'manage-database',
  NOT_FOUND: 'not-found',
  SIGN_IN: 'sigin-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  DISPENSE: 'dispense',
};
